version: "3"
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
  server:
    build: server/
    restart: always
    ports:
      - "3007:3007"
    volumes:
      - ./server:/server
      - /server/node_modules
    links:
      - mongo
  client:
    build: client/
    restart: always
    ports:
      - "3008:3008"
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      - PORT=3008
    links:
      - server
volumes:
  mongodata:
